### ISSUE TITLE
gold error

### ISSUE THREAD

**Issue by huimoran** [wbbeyourself/MAC-SQL#1]
Hello, when I was reading your paper, I saw that you mentioned "gold error", but I don't quite understand its meaning. 
Could you please explain it to me? You'd better give me an example to help me understand.

![gold error](https://github.com/wbbeyourself/MAC-SQL/assets/100472413/a161757f-2a1b-46bb-938d-a50ee82f95e1)

**Comment by wbbeyourself** [comment]
I will update the paper today, and give examples



---- Replied Message ----
| From | ***@***.***> |
| Date | 12/26/2023 10:03 |
| To | ***@***.***> |
| Cc | ***@***.***> |
| Subject | [wbbeyourself/MAC-SQL] gold error (Issue #1) |

Hello, when I was reading your paper, I saw that you mentioned "gold error", but I don't quite understand its meaning.
Could you please explain it to me? You'd better give me an example to help me understand.

gold.error.png (view on web)

**Comment by huimoran** [comment]
Ok, thank you very much.

**Comment by wbbeyourself** [comment]
I have just updated the paper, which will be available on arXiv in 2 days. Additionally, I have uploaded some bad cases to the latest code repository. Please take a look.

**Comment by huimoran** [comment]
Ok, thank you.
