### ISSUE TITLE
The sql-llama link in readme is not avaible

### ISSUE THREAD

**Issue by whitewum** [wbbeyourself/MAC-SQL#10]
https://huggingface.co/IceKingBing/SQL-Llama-v0.5 this link is broke. Any replacement?

**Comment by dragutin-oreski** [comment]
I'm curious about the same thing - where can we find the model?

I suppose it's not this one, right? - https://github.com/DominikLindorfer/SQL-LLaMA2

**Comment by basavarajsh98** [comment]
@whitewum @dragutin-oreski Did you guys find the model? I'm still looking. Please help me out!

**Comment by wbbeyourself** [comment]
Sorry for causing confusion to everyone. I will make the model available as soon as possible.

**Comment by basavarajsh98** [comment]
@wbbeyourself Thank you very much. That'd be great!

Also, to train the model, we should set the data_mode = train, right? I'm trying to train the model with the local model instead of using GPT4.

**Comment by wbbeyourself** [comment]
Hello everyone, thank you for waiting so patiently. The SQL-Llama-v0.5(7B) model has been released and you can now download and try it out. The link is https://huggingface.co/IceKingBing/SQL-Llama-v0.5. It should be noted that this version currently only uses 3000+ BIRD Instruct-Tuning data for fine-tuning (from the bird train set). The training script and data for this version will also be open-sourced in the next few days. Thank you again for your attention.
