### ISSUE TITLE
Selector few-shot prompts

### ISSUE THREAD

**Issue by Jannoshh** [wbbeyourself/MAC-SQL#12]
In your paper you use 2-shots for some experiments, e.g. in Table 4, but your code and the paper only has 1 shot for the selector. Did you use exactly 1 shot for all experiments with the selector?

**Comment by wbbeyourself** [comment]
We appreciate the feedback and acknowledge the lack of clarity in our paper. The term "2-shots" refers specifically to the Decomposer module, which we will explicitly state in the updated version of our paper.
