### ISSUE TITLE
关于微调数据的一些疑问

### ISSUE THREAD

**Issue by Semeron** [wbbeyourself/MAC-SQL#16]
作者，你好，项目中代码通过三个agent进行推理的代码，请问论文最后在训练sql-llama时，微调数据在三个aegnt的处理时，其中selector中的字段和表名可以通过标准的sql语句推断出来，该步骤微调数据的构造没问题，第二个agent——decomposer这一步对于现有的业务数据，我没有分解的数据，论文里面你训练时候，微调数据是怎么来的

**Comment by wbbeyourself** [comment]
decomposer 和 refiner 的训练数据 是调用 GPT-4 生成的，然后进行了筛选，保留了那些最终结果正确的数据。
