### ISSUE TITLE
请问，MAC-SQL是使用了OpenAI的API了，在内网/局域网或者离线状态下能够使用么？

### ISSUE THREAD

**Issue by kuazhangxiaoai** [wbbeyourself/MAC-SQL#18]
谢谢您的回答。

**Comment by wbbeyourself** [comment]
api的网络问题，这个您用一个简单例子测试就知道了。现在 OpenAI 对中国很多的接口对关闭了，看您使用的是哪个渠道的GPT-4，好多都封禁了。

**Comment by wbbeyourself** [comment]
如果你说的是不调用 OpenAI 的 API，调用内部模型接口服务，那是ok的，SQL-Llama 我就是部署在本地，然后调用接口的。
