### ISSUE TITLE
How much does it cost to use GPT-4 8k to complete the evaluation in the paper?

### ISSUE THREAD

**Issue by liiuzq-xiaobai** [wbbeyourself/MAC-SQL#2]
Thanks for your awesome work！I want to reproduce the result in the paper and make an evaluation of the corresponding call cost. Have you ever evaluated how much does it cost to use GPT-4-8k?

**Comment by wbbeyourself** [comment]
![mac-sql-token-usage](https://github.com/wbbeyourself/MAC-SQL/assets/18190695/ce04d5fc-1fe2-4071-9da1-3b0ca3864d39)

This data represents a rough estimate and is intended for reference purposes only. The costs are calculated based on the current pricing of OpenAI (as of December 27, 2022), and are approximately as indicated in the table above.

**Comment by wbbeyourself** [comment]
![pricing](https://github.com/wbbeyourself/MAC-SQL/assets/18190695/6cf660ec-0bcc-4c1a-83f0-bbf78316edef)

**Comment by liiuzq-xiaobai** [comment]
thanks

**Comment by wbbeyourself** [comment]
I change the default api version to `GPT-4-Turbo (128k)`, which is, on average, 2.5 times less expensive than the `GPT-4 (8k)` interface.
