### ISSUE TITLE
IceKingBing/SQL-Llama-v0.5模型得到结果与论文中结果差距较大

### ISSUE THREAD

**Issue by 290251949** [wbbeyourself/MAC-SQL#22]
您好，我在huggingface下载了模型IceKingBing/SQL-Llama-v0.5，按照github 仓库中readme部署运行后，在spider-dev验证集上得到结果为
![image](https://github.com/user-attachments/assets/4d79b695-02ba-4666-b77b-614950094e2c)
请问是需要调整什么参数吗？
以下是我的run文件，都是使用仓库的默认参数，期待您的回复
![image](https://github.com/user-attachments/assets/f54fda81-ae1d-4ab3-b2bb-b4c8d0791582)

**Comment by 290251949** [comment]
我使用的是这个模型https://huggingface.co/IceKingBing/SQL-Llama-v0.5

**Comment by wbbeyourself** [comment]
这个版本的SQL-Llama只加入了 BIRD 的数据，没有加入 spider 数据训练，所以在spider-dev 上效果不是最优的。完整版本的模型，我们会尽快release的。

**Comment by 290251949** [comment]
好的。谢谢您的回复
