### ISSUE TITLE
问题分解完成后如何聚合生成最终结果

### ISSUE THREAD

**Issue by Cha-01** [wbbeyourself/MAC-SQL#23]
在论文的附录中看到问题分解部分的prompt，该阶段的任务似乎只有分解子问题并解答子问题；请问生成最终答案时的prompt可以在哪里查看呢？

**Comment by wbbeyourself** [comment]
问题分解时是逐步分解的，由简单到负责，直到最后一个问题是原始用户的问题，也就是最后一个SQL就是最终的SQL，因此我们提取最后一个 SQL 即可。
