### ISSUE TITLE
Code flow

### ISSUE THREAD

**Issue by huimoran** [wbbeyourself/MAC-SQL#3]
Hello, excellent researcher. 

After reading your code, I want to know more about your work flow, but I have encountered difficulties when running your code.

Could you briefly introduce your overall code logic to me? I know this is a lot of trouble for you, and I'm very sorry.

**Comment by wbbeyourself** [comment]
The workflow is illustrated in our paper Figure 2 (MAC-SQL framework image).
Could you provide more details about your issues to let me understand?
Is it OpenAI config error or code exceptions?

**Comment by huimoran** [comment]
Yes, I have seen the flow chart and text introduction in your paper. I have also successfully run the experiment, obtained the SQL statement of large model prediction and conducted the evaluation. 

But I don't understand the logic of the code very well, and I have encountered difficulties in the process of learning your code. Could you tell me the process from run.py file to calling various files in the core folder.

![liu](https://github.com/wbbeyourself/MAC-SQL/assets/100472413/ddb0d509-0cb0-475f-95fb-8821ff18ac58)

**Comment by wbbeyourself** [comment]
Thank you for your attention, I understand your point. I will update the README in the next few days to introduce the functionality and purpose of the core modules in the project structure, and will inform you promptly after the update.

**Comment by wbbeyourself** [comment]
Readme is updated. Please take a look.

**Comment by huimoran** [comment]
Yes, I see. Thank you.
