### ISSUE TITLE
Are instruction-tuned models available

### ISSUE THREAD

**Issue by shuaichenchang** [wbbeyourself/MAC-SQL#4]
Thank you for the great work! I wonder whether the instruction-tuned models are available now and how well they perform on the text2sql datasets?

**Comment by wbbeyourself** [comment]
Thank you for your attention. The model files and related results are currently being compiled and will be made available in the next version of the paper. We will inform you promptly once the update is completed.

**Comment by ermlickw** [comment]
checking status of this please. it looks like the model was uploaded [here](https://huggingface.co/IceKingBing/SQL-Llama-v0.5) and taken down.
