### ISSUE TITLE
Improving Dataset Accessibility on Google Drive

### ISSUE THREAD

**Issue by MNIKIEMA** [wbbeyourself/MAC-SQL#5]
Hello,

I appreciate the work on this project and recently requested access to the dataset on Google Drive. To facilitate smoother and faster access, could we consider simplifying the current request-based access method?

Understanding the balance between ease of access and data security, I'd be interested in hearing your thoughts on this suggestion.

Thank you for considering this enhancement.

Best regards,
Mahamadi

**Comment by wbbeyourself** [comment]
Thank you for your attention. We have open-sourced the SQL-Llama-Instruct-v0.5.jsonl data and training script, as well as the v0.5 version of SQL-Llama. Please check out our latest commit.
