### ISSUE TITLE
Help wanted! I can't reproduce your results on Spider dev as shown in the paper

### ISSUE THREAD

**Issue by bdiva** [wbbeyourself/MAC-SQL#7]
I have followed the code in your script, but the results I get are not quite right. I wonder if there are other parameters? Is there any way to improve this? Can you help me solve this problem? Thank you.

```count                248                  446                  174                  166                  1034                
=====================   EXECUTION ACCURACY     =====================
execution            0.911                0.814                0.759                0.651                0.802               

====================== EXACT MATCHING ACCURACY =====================
exact match          0.069                0.007                0.000                0.000                0.019               

---------------------PARTIAL MATCHING ACCURACY----------------------
select               1.000                1.000                0.000                0.000                0.952               
select(no AGG)       1.000                1.000                0.000                0.000                0.952               
where                0.000                1.000                0.000                1.000                1.000               
where(no OP)         0.000                1.000                0.000                1.000                1.000               
group(no Having)     0.000                0.000                0.000                0.000                0.000               
group                0.000                0.000                0.000                0.000                0.000               
order                0.000                0.000                0.000                0.000                0.000               
and/or               1.000                0.899                0.897                0.880                0.920               
IUEN                 0.000                0.000                0.000                0.000                0.000               
keywords             0.000                1.000                0.000                1.000                1.000               
---------------------- PARTIAL MATCHING RECALL ----------------------
select               0.069                0.007                0.000                0.000                0.019               
select(no AGG)       0.069                0.007                0.000                0.000                0.019               
where                0.000                0.016                0.000                0.011                0.008               
where(no OP)         0.000                0.016                0.000                0.011                0.008               
group(no Having)     0.000                0.000                0.000                0.000                0.000               
group                0.000                0.000                0.000                0.000                0.000               
order                0.000                0.000                0.000                0.000                0.000               
and/or               1.000                1.000                1.000                1.000                1.000               
IUEN                 0.000                0.000                0.000                0.000                0.000               
keywords             0.000                0.008                0.000                0.006                0.005               
---------------------- PARTIAL MATCHING F1 --------------------------
select               0.128                0.013                1.000                1.000                0.038               
select(no AGG)       0.128                0.013                1.000                1.000                0.038               
where                1.000                0.032                1.000                0.021                0.017               
where(no OP)         1.000                0.032                1.000                0.021                0.017               
group(no Having)     1.000                1.000                1.000                1.000                1.000               
group                1.000                1.000                1.000                1.000                1.000               
order                1.000                1.000                1.000                1.000                1.000               
and/or               1.000                0.947                0.945                0.936                0.958               
IUEN                 1.000                1.000                1.000                1.000                1.000               
keywords             1.000                0.016                1.000                0.012                0.009

**Comment by zhihui-shao** [comment]
@bdiva Does it take a long time to evaluate the Spider dataset? I've been running it for two days and still no results

**Comment by wbbeyourself** [comment]
> @bdiva Does it take a long time to evaluate the Spider dataset? I've been running it for two days and still no results

In my experiments, it usually takes 5-7 hours to evaluate Spider dev (1034 examples).

**Comment by wbbeyourself** [comment]
> > > @bdiva Does it take a long time to evaluate the Spider dataset? I've been running it for two days and still no results
> > 
> > 
> > In my experiments, it usually takes 5-7 hours to evaluate Spider dev (1034 examples). Please provide more log details to locate the problem.
> 
> ![image](https://private-user-images.githubusercontent.com/121287193/307591721-860c994f-fd4d-46a0-8647-6c5c6bd57d7d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg4NjkzMzMsIm5iZiI6MTcwODg2OTAzMywicGF0aCI6Ii8xMjEyODcxOTMvMzA3NTkxNzIxLTg2MGM5OTRmLWZkNGQtNDZhMC04NjQ3LTZjNWM2YmQ1N2Q3ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyNVQxMzUwMzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZTEwOWNkMWU5ZDAxMzM3NWRiMDE5NjE5MmJjYTk5NzViMjQxYjA2NWU5M2IwNzE5N2FjZmU2ZjEzYzM4ZDc3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.GkZUKqwQPuQh4obLkXmkHnmo5_LYJARQNuBQFJUtFk0) 一直卡在这里，两天了。请问你是用什么硬件跑的

我刚才修复了 evaluate_spider 里的问题，卡住是因为 exec_eval.py 中 
```
_, preds = get_all_preds_for_execution(g_str, p_str)
```
这行代码会产生大量可能的pred变体，如果数量非常多，就会卡在这里，只要控制数量及时 break 出去即可。一般是错误的 SQL 导致 代码执行时间超时，很多条这样的，就会卡住很久。我加了 max_try = 50 （exec_eval.py line 213） ，表示最多尝试50种变体，你可以看具体情况改改。

**Comment by zhihui-shao** [comment]
> 我刚才修复了 evaluate_spider 里的问题，卡住是因为 exec_eval.py 中
> 
> ```
> _, preds = get_all_preds_for_execution(g_str, p_str)
> ```
> 
> 这行代码会产生大量可能的pred变体，如果数量非常多，就会卡在这里，只要控制数量及时 break 出去即可。一般是错误的 SQL 导致 代码执行时间超时，很多条这样的，就会卡住很久。我加了 max_try = 50 （exec_eval.py line 213） ，表示最多尝试50种变体，你可以看具体情况改改。

非常感谢你的修改，我成功跑出结果了，但似乎距离文章中的数据有点差别，您能帮我看看原因吗？
![image](https://github.com/wbbeyourself/MAC-SQL/assets/121287193/d3da82d1-6dd1-4a14-b24f-c7241fb96176)

**Comment by wbbeyourself** [comment]
请问您这次结果用的是其中哪个模型？
 ['gpt-4-1106-preview',  'gpt-4-32k', 'gpt-4',  'gpt-35-turbo-16k']  
 GPT-4 和 GPT-3.5-turbo 的结果会存在一定差距，另外请查看模型的具体日期版本，我实验中使用的是 0613 版本。

**Comment by zhihui-shao** [comment]
> 请问您这次结果用的是其中哪个模型？ ['gpt-4-1106-preview', 'gpt-4-32k', 'gpt-4', 'gpt-35-turbo-16k'] GPT-4 和 GPT-3.5-turbo 的结果会存在一定差距，另外请查看模型的具体日期版本，我实验中使用的是 0613 版本。

我用的是公司申请的模型，应该是gpt-4-turbo

**Comment by wbbeyourself** [comment]
论文中标出的最优结果是基于 GPT-4-32k 跑出来的，后续因为 GPT-4-32k 成本太高，因此在代码中将默认模型改成了 gpt-4-1106-preview (即 GPT-4-turbo) ，GPT-4-32k 总体上会比 GPT-4-Turbo 的更优一些。
