### ISSUE TITLE
Help！I want to know  in the agents name 'parse_single_sql' is not defined. i don't find it in other code. please!!!

### ISSUE THREAD

**Issue by PanYuQi66666666** [wbbeyourself/MAC-SQL#9]
Help！I want to know  in the agents name 'parse_single_sql' is not defined. i don't find it in other code. please!!!

**Comment by wbbeyourself** [comment]
I just fix it by using parse_sql_from_string. Please pull the latest commit and check it  out.

**Comment by PanYuQi66666666** [comment]
@wbbeyourself 
![image](https://github.com/wbbeyourself/MAC-SQL/assets/77387991/4fac0bc8-1ef8-4e4c-8829-14ebfd098207)
Replace module parse_single_sql with module parse_sql_from_string?

**Comment by wbbeyourself** [comment]
yes
